<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a3e6f2d4-5c8b-4b0a-9c1e-6f9d2b7a4e10</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="FastEndpoints" />
    <PackageReference Include="FastEndpoints.Security" />
    <PackageReference Include="FastEndpoints.Swagger" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Mediator.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppTemplate.Core\AppTemplate.Core.csproj" />
    <ProjectReference Include="..\AppTemplate.Infrastructure\AppTemplate.Infrastructure.csproj" />
    <ProjectReference Include="..\AppTemplate.SharedKernel\AppTemplate.SharedKernel.csproj" />
    <ProjectReference Include="..\AppTemplate.UseCases\AppTemplate.UseCases.csproj" />
    <ProjectReference Include="..\AppTemplate.ServiceDefaults\AppTemplate.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
