/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete a user
     * @description Deletes a user with the specified id.
     */
    delete: operations['AppTemplateWebFeaturesUserFeaturesDeleteEndpoint'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a user by Id
     * @description Get a user with the specified Id.
     */
    get: operations['AppTemplateWebFeaturesUserFeaturesGetByIdEndpoint'];
    /**
     * Update a user
     * @description Updates a user's name and, optionally, phone number (which needs a country code). Users may update their own profile; updating anyone else's requires the users:write permission.
     */
    put: operations['AppTemplateWebFeaturesUserFeaturesUpdateEndpoint'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List users with pagination
     * @description Retrieves a paginated list of all users. Supports GitHub-style pagination with 1-based page indexing and configurable page size.
     */
    get: operations['AppTemplateWebFeaturesUserFeaturesListEndpoint'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the current user
     * @description Returns the authenticated caller's profile, creating it from the access token's claims on first call.
     */
    get: operations['AppTemplateWebFeaturesUserFeaturesMeEndpoint'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/outbox/dead-letters/requeue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Requeue dead-lettered outbox messages
     * @description Makes every dead-lettered outbox message due again with a fresh attempt count, and returns how many.
     */
    post: operations['AppTemplateWebFeaturesOutboxFeaturesRequeueDeadLetteredMessagesEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/jobs/{jobId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a recurring job
     * @description The job's schedule and its most recent runs.
     */
    get: operations['AppTemplateWebFeaturesJobFeaturesGetJobEndpoint'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List recurring background jobs
     * @description Every scheduled recurring job with its schedule, next and last run.
     */
    get: operations['AppTemplateWebFeaturesJobFeaturesListJobsEndpoint'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/jobs/{JobId}/pause': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Pause a recurring job
     * @description Skips scheduled runs until resumed; the schedule itself is kept. Survives restarts; pausing twice is a no-op.
     */
    post: operations['AppTemplateWebFeaturesJobFeaturesPauseJobEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/jobs/{JobId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove a recurring job
     * @description Removes the job from the scheduler until the next restore or restart (definitions live in code).
     */
    delete: operations['AppTemplateWebFeaturesJobFeaturesRemoveJobEndpoint'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/jobs/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore all recurring jobs
     * @description Re-registers every job definition (e.g. after removing one), keeping paused jobs paused.
     */
    post: operations['AppTemplateWebFeaturesJobFeaturesRestoreJobsEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/jobs/{JobId}/resume': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resume a recurring job
     * @description Scheduled runs happen again. Resuming a job that isn't paused is a no-op.
     */
    post: operations['AppTemplateWebFeaturesJobFeaturesResumeJobEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/jobs/{JobId}/trigger': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run a recurring job now
     * @description Enqueues an immediate run without changing the schedule; works while paused.
     */
    post: operations['AppTemplateWebFeaturesJobFeaturesTriggerJobEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password reset email
     * @description If an account uses the given email, Keycloak sends it a link to set a new password. The response is the same whether or not the account exists.
     */
    post: operations['AppTemplateWebFeaturesAuthenticationFeaturesForgotPasswordEndpoint'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List audit entries
     * @description Entity changes and security events, newest first. Filter by entity, actor and time range (default: the last 7 days).
     */
    get: operations['AppTemplateWebFeaturesAuditFeaturesListAuditEntriesEndpoint'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
    } & {
      [key: string]: unknown;
    };
    DeleteUserRequest: Record<string, never>;
    UserRecord: {
      /** Format: int32 */
      id: number;
      name: string;
      phoneNumber?: string | null;
    };
    GetUserByIdRequest: Record<string, never>;
    UserListResponse: components['schemas']['PagedResultOfUserRecord'] & Record<string, never>;
    PagedResultOfUserRecord: {
      items: components['schemas']['UserRecord'][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      perPage: number;
      /** Format: int32 */
      totalCount: number;
      /** Format: int32 */
      totalPages: number;
    };
    ListUsersRequest: Record<string, never>;
    CurrentUserResponse: {
      /** Format: int32 */
      id: number;
      name: string;
      email: string;
      permissions: string[];
    };
    UpdateUserResponse: {
      user: components['schemas']['UserRecord'];
    };
    /**
     * @example {
     *       "name": "Sample User",
     *       "phoneNumber": "555 0100",
     *       "phoneCountryCode": "+1",
     *       "phoneExtension": null
     *     }
     */
    UpdateUserRequest: {
      /** @example Sample User */
      name: string;
      /** @example 555 0100 */
      phoneNumber?: string | null;
      /** @example +1 */
      phoneCountryCode?: string | null;
      /** @example null */
      phoneExtension?: string | null;
    };
    RequeueDeadLetteredMessagesResponse: {
      /** Format: int32 */
      requeued: number;
    };
    RecurringJobDetailResponse: {
      job: components['schemas']['RecurringJobResponse'];
      recentExecutions: components['schemas']['JobExecutionResponse'][];
    };
    RecurringJobResponse: {
      id: string;
      cron: string;
      /** Format: date-time */
      nextExecution?: string | null;
      /** Format: date-time */
      lastExecution?: string | null;
      lastStatus?: string | null;
      isPaused: boolean;
      /** Format: date-time */
      createdAt?: string | null;
    };
    JobExecutionResponse: {
      jobId: string;
      status: string;
      /** Format: date-time */
      finishedAt?: string | null;
      /** Format: double */
      durationMs?: number | null;
      error?: string | null;
    };
    HttpValidationProblemDetails: components['schemas']['ProblemDetails'] &
      ({
        errors: {
          [key: string]: string[];
        };
      } & {
        [key: string]: unknown;
      });
    JobIdRequest: Record<string, never>;
    /**
     * @example {
     *       "email": "sample.user@example.com"
     *     }
     */
    ForgotPasswordRequest: {
      /** @example sample.user@example.com */
      email: string;
    };
    PagedResultOfAuditEntryDto: {
      items: components['schemas']['AuditEntryDto'][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      perPage: number;
      /** Format: int32 */
      totalCount: number;
      /** Format: int32 */
      totalPages: number;
    };
    AuditEntryDto: {
      /** Format: guid */
      id: string;
      /** Format: date-time */
      occurredAtUtc: string;
      actor: string;
      action: string;
      entityType: string;
      entityKey: string;
      outcome: string;
      changes?: {
        [key: string]: components['schemas']['AuditValueChange'];
      } | null;
      traceId?: string | null;
    };
    AuditValueChange: {
      old?: string | null;
      new?: string | null;
    };
    ListAuditEntriesRequest: Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppTemplateWebFeaturesUserFeaturesDeleteEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1 */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the users:delete permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  AppTemplateWebFeaturesUserFeaturesGetByIdEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1 */
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User obtained successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": 1,
           *       "name": "Sample User",
           *       "phoneNumber": null
           *     }
           */
          'application/json': components['schemas']['UserRecord'];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the users:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  AppTemplateWebFeaturesUserFeaturesUpdateEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 1 */
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        '*/*': components['schemas']['UpdateUserRequest'];
      };
    };
    responses: {
      /** @description User updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "user": {
           *         "id": 1,
           *         "name": "Sample User",
           *         "phoneNumber": "+1 555 0100"
           *       }
           *     }
           */
          'application/json': components['schemas']['UpdateUserResponse'];
        };
      };
      /** @description Invalid request data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not your profile, and no users:write permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  AppTemplateWebFeaturesUserFeaturesListEndpoint: {
    parameters: {
      query: {
        /**
         * @description 1-based page index (default 1)
         * @example 1
         */
        page: number;
        /** @example 10 */
        per_page: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of users returned successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "items": [
           *         {
           *           "id": 1,
           *           "name": "Sample User 1",
           *           "phoneNumber": null
           *         },
           *         {
           *           "id": 2,
           *           "name": "Sample User 2",
           *           "phoneNumber": null
           *         }
           *       ],
           *       "page": 1,
           *       "perPage": 10,
           *       "totalCount": 2,
           *       "totalPages": 1
           *     }
           */
          'application/json': components['schemas']['UserListResponse'];
        };
      };
      /** @description Invalid pagination parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the users:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesUserFeaturesMeEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user returned successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          /**
           * @example {
           *       "id": 1,
           *       "name": "Sample User",
           *       "email": "sample@example.com",
           *       "permissions": [
           *         "users:read"
           *       ]
           *     }
           */
          'application/json': components['schemas']['CurrentUserResponse'];
        };
      };
      /** @description The access token is missing a required claim */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description The token's email is already linked to another user */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  AppTemplateWebFeaturesOutboxFeaturesRequeueDeadLetteredMessagesEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Messages requeued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RequeueDeadLetteredMessagesResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the jobs:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesJobFeaturesGetJobEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The job with its recent runs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecurringJobDetailResponse'];
        };
      };
      /** @description Invalid job id */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the jobs:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesJobFeaturesListJobsEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Recurring jobs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecurringJobResponse'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the jobs:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesJobFeaturesPauseJobEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paused */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid job id */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the jobs:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesJobFeaturesRemoveJobEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid job id */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the jobs:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesJobFeaturesRestoreJobsEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Jobs restored */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the jobs:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesJobFeaturesResumeJobEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Resumed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid job id */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the jobs:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesJobFeaturesTriggerJobEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Run enqueued */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid job id */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the jobs:manage permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AppTemplateWebFeaturesAuthenticationFeaturesForgotPasswordEndpoint: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordRequest'];
      };
    };
    responses: {
      /** @description Request accepted; an email is sent if the account exists */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid email */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Too many requests */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description The identity provider is unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  AppTemplateWebFeaturesAuditFeaturesListAuditEntriesEndpoint: {
    parameters: {
      query: {
        entityType?: string | null;
        entityKey?: string | null;
        actor?: string | null;
        from?: string | null;
        to?: string | null;
        page: number;
        per_page: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A page of audit entries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PagedResultOfAuditEntryDto'];
        };
      };
      /** @description Invalid filter or page */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['HttpValidationProblemDetails'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Requires the audit:read permission */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
